---
- name: restart nomad
  become: yes
  become_user: "{{ nomad_user }}"
  service:
    name: nomad
    state: restarted

- name: reload systemd
  become: yes
  become_user: "{{ nomad_user }}"
  command: systemctl daemon-reload
